### ISSUE TITLE
Exponential Backoff seems backwards

### ISSUE THREAD

**Issue by jboyens** [jfiander/exp-retry#1]
With `retries: 3`, the first time it receives the exception it will wait 8 seconds. The second time it only waits 4 seconds, the third retry will only wait 2 seconds.

I think that logic is backwards. It should go 2,4,8 not 8,4,2.

You want to delay by the number of times you've retried, not the number of retries you have left.

**Comment by jfiander** [comment]
Yep, good catch! I missed that when I was doing some cleanup.
